'use strict';
const M=JKModel,MASTER_KEY='JK_GESTAO_MASTER';
const SUPABASE_URL='https://paelenmndnwgnlbvqxrs.supabase.co';
const SUPABASE_KEY='sb_publishable_rG8rH2EZytvDBF4tqIJ6kQ_yYJU7MXN';
const SHARED_ENDPOINT=SUPABASE_URL+'/rest/v1/jk_shared_state?id=eq.main';
const $=s=>document.querySelector(s),uid=()=>crypto.randomUUID();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const fmt=s=>s?s.slice(0,10).split('-').reverse().join('/'):'não informada';
let DB=M.base(),cloudReady=false,cloudSaving=false,revision=null,editingClientId=null,editingOfferingId=null,paymentVisitId=null,selectedDay=null;
let calCursor=new Date();calCursor.setDate(1);
const client=id=>DB.clients.find(c=>c.id===id),offering=id=>DB.offerings.find(o=>o.id===id);
const visitName=s=>s.offeringName||offering(s.offeringId)?.name||'Serviço';
const sortedClients=()=>[...DB.clients].sort((a,b)=>a.name.localeCompare(b.name));
const clientOptions=(placeholder='Selecione o cliente')=>`<option value="">${placeholder}</option>`+sortedClients().map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');
function status(text){$('#syncStatus').textContent=text}
function cache(){localStorage.setItem(MASTER_KEY,JSON.stringify(DB))}
async function loadCloud(){const r=await fetch(SHARED_ENDPOINT+'&select=data,updated_at',{headers:{apikey:SUPABASE_KEY},cache:'no-store'});if(!r.ok)throw Error('Não foi possível carregar os dados compartilhados.');const row=(await r.json())[0];if(!row?.data)throw Error('Banco compartilhado não encontrado.');return row}
async function bootShared(){try{const raw=localStorage.getItem(MASTER_KEY);if(raw)DB=M.migrate(JSON.parse(raw))}catch{}renderAll();try{const row=await loadCloud();DB=M.migrate(row.data);revision=row.updated_at;cloudReady=true;cache();status('Dados sincronizados.');renderAll()}catch(e){status('Sem conexão. Dados salvos neste aparelho, somente para consulta. Atualize a página para tentar novamente.')}}
async function refreshCloud(){if(!cloudReady||cloudSaving||document.querySelector('dialog[open]'))return;try{const row=await loadCloud();if(row.updated_at!==revision){DB=M.migrate(row.data);revision=row.updated_at;cache();renderAll();status('Dados sincronizados.')}}catch{status('Conexão instável. Verifique a conexão antes de salvar.')}}
async function commit(change){
 if(!cloudReady){alert('Aguarde a conexão com os dados compartilhados antes de salvar.');return false}
 if(cloudSaving)return false;
 const next=JSON.parse(JSON.stringify(DB));
 try{change(next);M.validate(next)}catch(e){alert(e.message);return false}
 cloudSaving=true;status('Salvando…');
 try{
  const r=await fetch(SHARED_ENDPOINT+'&updated_at=eq.'+encodeURIComponent(revision),{method:'PATCH',headers:{apikey:SUPABASE_KEY,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({data:next,updated_at:new Date().toISOString()})});
  if(!r.ok)throw Error('Não foi possível salvar. Seus dados anteriores foram mantidos; confira a conexão e tente novamente.');
  const rows=await r.json();if(!rows.length){const row=await loadCloud();DB=M.migrate(row.data);revision=row.updated_at;cache();renderAll();throw Error('Os dados foram atualizados em outro aparelho. A versão atual foi carregada; confira e repita esta alteração.');}
  DB=M.migrate(rows[0].data);revision=rows[0].updated_at;cache();renderAll();status('Dados sincronizados.');return true;
 }catch(e){status('Alteração não confirmada. '+e.message);alert(e.message);return false}finally{cloudSaving=false}
}
function goPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));if(id==='agenda')renderAgenda()}
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>goPage(b.dataset.page));
function scheduleState(o){return !o.nextDue?'Sem previsão':o.nextDue<M.today()?'Atrasado • não realizado':o.nextDue===M.today()?'Previsto para hoje':'Agendado'}
function scheduled(){return DB.offerings.filter(o=>o.nextDue).sort((a,b)=>a.nextDue.localeCompare(b.nextDue))}
function scheduleItem(o){return `<div class="item"><div class="left"><div class="title">${esc(client(o.clientId)?.name)}</div><div class="serviceName">${esc(o.name)}</div><div class="meta">${fmt(o.nextDue)} • ${scheduleState(o)}<br>${esc(client(o.clientId)?.address)}</div></div><button class="secondary" onclick="openDone('${o.id}')">Registrar realizado</button></div>`}
function renderAll(){renderMetrics();renderClients();renderOfferings();renderDashboard();renderFinance();renderHistory();renderAgenda()}
function renderMetrics(){
 $('#mClients').textContent=DB.clients.length;$('#mLate').textContent=scheduled().filter(o=>o.nextDue<M.today()).length;$('#mReceive').textContent=money(M.totalPending(DB));$('#mPaid').textContent=money(M.paidMonth(DB));
 const end=new Date(M.today()+'T12:00:00');end.setDate(end.getDate()+7);$('#mWeek').textContent=scheduled().filter(o=>o.nextDue>=M.today()&&new Date(o.nextDue+'T12:00:00')<=end).length;
}
function renderClients(){const q=M.key($('#clientSearch').value);const list=sortedClients().filter(c=>!q||M.key(c.name+' '+c.address).includes(q));$('#clientList').innerHTML=list.map(c=>`<div class="customerCard"><div class="name">${esc(c.name)}</div><div class="minor">${esc(c.address)}</div><div class="rowActions"><button class="primary" onclick="showOfferings('${c.id}')">Serviços (${DB.offerings.filter(o=>o.clientId===c.id).length})</button><button class="ghost" onclick="openClient('${c.id}')">Editar cliente</button></div></div>`).join('')||'<div class="empty">Nenhum cliente encontrado.</div>'}
function renderOfferings(){const f=$('#offeringFilter').value;$('#offeringFilter').innerHTML=clientOptions('Todos os clientes');$('#offeringFilter').value=client(f)?f:'';const q=M.key($('#offeringSearch').value);$('#offeringList').innerHTML=DB.offerings.filter(o=>(!$('#offeringFilter').value||o.clientId===$('#offeringFilter').value)&&(!q||M.key(o.name).includes(q))).map(o=>`<div class="offeringCard"><div class="name">${esc(client(o.clientId)?.name)}</div><div class="serviceName">${esc(o.name)}</div><div class="minor">${esc(o.freq)} • ${money(o.value)}<br>Próxima visita: ${o.nextDue?fmt(o.nextDue):'sem previsão'} • ${scheduleState(o)}</div><div class="rowActions"><button class="secondary" onclick="openDone('${o.id}')">Registrar visita</button><button class="ghost" onclick="openOffering('${o.id}')">Editar serviço</button></div></div>`).join('')||'<div class="empty">Nenhum serviço cadastrado. Use “Novo serviço”.</div>'}
function showOfferings(id){$('#offeringFilter').value=id;renderOfferings();goPage('offerings')}
function openClient(id=null){editingClientId=id;const c=client(id);$('#clientDlgTitle').textContent=c?'Editar cliente':'Novo cliente';$('#cName').value=c?.name||'';$('#cCity').value=c?.address||'';clientDialog.showModal()}
async function saveClient(){const input={id:uid(),name:$('#cName').value,address:$('#cCity').value};let saved;if(await commit(db=>{saved=M.saveClient(db,input,editingClientId)})){clientDialog.close();if(!editingClientId)showOfferings(saved.id)}}
function openOffering(id=null){editingOfferingId=id;const o=offering(id);$('#offeringTitle').textContent=o?'Editar serviço':'Novo serviço';$('#oClient').innerHTML=clientOptions();$('#oClient').value=o?.clientId||$('#offeringFilter').value||'';$('#oClient').disabled=!!o;$('#oName').value=o?.name||'';$('#oFreq').value=o?.freq||'Avulso';$('#oValue').value=o?.value??'';$('#oNext').value=o?.nextDue||'';offeringDialog.showModal()}
$('#oFreq').onchange=()=>{const o=offering(editingOfferingId),last=o&&M.visitsFor(DB,o.id).at(-1);if(last)$('#oNext').value=M.nextDate(last.date,$('#oFreq').value)};
async function saveOffering(){const input={id:uid(),clientId:$('#oClient').value,name:$('#oName').value,freq:$('#oFreq').value,value:$('#oValue').value,nextDue:$('#oNext').value};if(await commit(db=>M.saveOffering(db,input,editingOfferingId))){offeringDialog.close();showOfferings(input.clientId)}}
function openDone(offeringId=null){const o=offering(offeringId);$('#doneClientSelect').innerHTML=clientOptions();$('#doneClientSelect').value=o?.clientId||$('#offeringFilter').value||'';$('#doneDate').value=M.today();$('#doneDate').max=M.today();$('#doneNotes').value='';selectDoneClient($('#doneClientSelect').value);if(o){$('#doneOfferingSelect').value=o.id;selectDoneOffering(o.id)}doneDialog.showModal()}
function selectDoneClient(id){const arr=DB.offerings.filter(o=>o.clientId===id);$('#doneOfferingSelect').innerHTML='<option value="">Selecione o serviço</option>'+arr.map(o=>`<option value="${esc(o.id)}">${esc(o.name)} • ${money(o.value)}</option>`).join('');if(arr.length===1)$('#doneOfferingSelect').value=arr[0].id;selectDoneOffering($('#doneOfferingSelect').value)}
function selectDoneOffering(id){const o=offering(id);$('#doneValue').value=o?.value??'';$('#doneHint').textContent=!o?'Selecione o cliente e o serviço.':o.freq==='Quinzenal'?(M.visitsFor(DB,o.id).some(s=>s.cyclePosition===1&&!s.cycleClosed)?'2ª visita deste serviço: gera a cobrança do ciclo.':'1ª visita deste serviço: ainda não gera cobrança.'):'A visita realizada gera uma cobrança deste serviço.'}
async function confirmDone(){const id=$('#doneOfferingSelect').value,input={id:uid(),date:$('#doneDate').value,amount:$('#doneValue').value,note:$('#doneNotes').value.trim()};if(await commit(db=>M.complete(db,id,input)))doneDialog.close()}
function renderDashboard(){$('#dashAgenda').innerHTML=scheduled().slice(0,6).map(scheduleItem).join('')||'<div class="empty">Sem próximas visitas.</div>';$('#dashPending').innerHTML=M.pending(DB).slice(0,6).map(s=>chargeItem(s,false)).join('')||'<div class="empty">Nenhuma cobrança pendente.</div>'}
function chargeItem(s,action=true){return `<div class="item"><div class="left"><div class="title">${esc(client(s.clientId)?.name)}</div><div class="serviceName">${esc(visitName(s))}</div><div class="meta">Visita: ${fmt(s.date)}${s.cyclePosition===2?' • 2ª visita do ciclo':''}</div></div><div><div class="amount pendingAmount">${money(s.amount)}</div>${action?`<button class="primary" onclick="markPaid('${s.id}')">Registrar pagamento</button>`:''}</div></div>`}
function renderFinance(){const pend=M.pending(DB);$('#fPending').textContent=money(M.totalPending(DB));$('#fPaid').textContent=money(M.paidMonth(DB));$('#fCount').textContent=pend.length;$('#financeList').innerHTML=pend.map(s=>chargeItem(s)).join('')||'<div class="empty">Nenhuma cobrança pendente.</div>';$('#receivedList').innerHTML=[...M.activePayments(DB)].sort((a,b)=>(b.date||'').localeCompare(a.date||'')).map(p=>`<div class="item"><div class="left"><div class="title">${esc(p.clientName||client(p.clientId)?.name)}</div><div class="serviceName">${esc(p.offeringName||offering(p.offeringId)?.name)}</div><div class="meta">Pagamento: ${fmt(p.date)} • Visita: ${fmt(DB.services.find(s=>s.id===p.serviceId)?.date)}</div></div><div><div class="amount">${money(p.amount)}</div><button class="danger" onclick="undoPayment('${p.id}')">Desfazer pagamento</button></div></div>`).join('')||'<div class="empty">Nenhum recebimento registrado.</div>'}
function renderHistory(){const q=M.key($('#historySearch').value);$('#historyList').innerHTML=[...DB.services].sort((a,b)=>b.date.localeCompare(a.date)).filter(s=>!q||M.key(client(s.clientId)?.name+' '+visitName(s)).includes(q)).map(s=>{
 const payments=M.activePayments(DB).filter(p=>p.serviceId===s.id),reversals=DB.payments.filter(p=>p.serviceId===s.id&&p.reversedAt);
 let state=s.chargeDue?(s.paid?'Pago':'Não pago • A receber'):'1ª visita • cobrança na 2ª visita';
 const second=!s.chargeDue&&DB.services.find(v=>v.cycleFirstId===s.id);if(second)state+=' • ciclo '+(second.paid?'pago':'a receber');
 const dates=payments.length?payments.map(p=>`${fmt(p.date)} (${money(p.amount)})`).join(', '):s.chargeDue&&s.paid?'não informada no histórico':'';
 const actions=s.chargeDue?(s.paid?(payments.length?payments.map(p=>`<button class="danger" onclick="undoPayment('${p.id}')">Desfazer pagamento</button>`).join(''):`<button class="danger" onclick="undoLegacyPayment('${s.id}')">Desfazer pagamento histórico</button>`):`<button class="primary" onclick="markPaid('${s.id}')">Registrar pagamento</button>`):payments.map(p=>`<button class="danger" onclick="undoPayment('${p.id}')">Desfazer pagamento histórico</button>`).join('');
 return `<div class="item visitItem"><div class="left"><div class="title">${esc(client(s.clientId)?.name)}</div><div class="serviceName">${esc(visitName(s))}</div><div class="meta">${fmt(s.date)} • Realizado${s.cyclePosition?' • '+s.cyclePosition+'ª visita do ciclo':''}<br>${state}${dates?'<br>Pagamento: '+dates:''}${s.note?'<br>'+esc(s.note):''}${reversals.length?'<br>'+reversals.length+' pagamento(s) desfeito(s)':''}</div><div class="rowActions">${actions}</div></div><div class="amount">${money(s.amount)}</div></div>`;
 }).join('')||'<div class="empty">Nenhuma visita realizada.</div>'}
function markPaid(id){const s=DB.services.find(s=>s.id===id);if(!s)return;paymentVisitId=id;$('#paymentSummary').textContent=`Confirmar recebimento de ${money(s.amount)} de ${client(s.clientId)?.name}? ${visitName(s)} — visita de ${fmt(s.date)}.`;$('#paymentDate').value=M.today();$('#paymentDate').min=s.date;$('#paymentDate').max=M.today();paymentDialog.showModal()}
async function confirmPayment(){const input={paymentId:uid(),date:$('#paymentDate').value};if(await commit(db=>M.pay(db,paymentVisitId,input)))paymentDialog.close()}
async function undoPayment(id){const p=DB.payments.find(p=>p.id===id);if(p&&confirm(`Desfazer ${money(p.amount)} de ${p.clientName||client(p.clientId)?.name}? A visita será mantida.`))await commit(db=>M.undo(db,id))}
async function undoLegacyPayment(id){const s=DB.services.find(s=>s.id===id);if(s&&confirm(`Desfazer o pagamento histórico de ${money(s.amount)} de ${client(s.clientId)?.name}? A data original não foi informada. A visita será mantida.`))await commit(db=>M.undoLegacy(db,id,uid()))}
function renderAgenda(){const y=calCursor.getFullYear(),m=calCursor.getMonth();$('#monthTitle').textContent=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(calCursor);const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),end=new Date(y,m+1,0),total=Math.ceil((first.getDay()+end.getDate())/7)*7;let out=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'].map(x=>`<div class="calHead">${x}</div>`).join('');for(let i=0;i<total;i++){const d=new Date(start);d.setDate(d.getDate()+i);const ds=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-'),planned=DB.offerings.filter(o=>o.nextDue===ds),done=DB.services.filter(s=>s.date===ds);out+=`<button class="day${d.getMonth()!==m?' muted':''}${ds===M.today()?' today':''}${ds===selectedDay?' selected':''}" aria-label="${fmt(ds)}: ${planned.length} previstas, ${done.length} realizadas" onclick="selectDay('${ds}')"><div class="dayNum">${d.getDate()}</div><span class="dayCount">${planned.length?planned.length+' prev.':''}${done.length?'<br>✓ '+done.length:''}</span>${planned.map(o=>`<div class="event" title="${esc(client(o.clientId)?.name+' • '+o.name)}">${esc(client(o.clientId)?.name)} • ${esc(o.name)}</div>`).join('')}</button>`}$('#calendar').innerHTML=out;$('#lateList').innerHTML=scheduled().filter(o=>o.nextDue<M.today()).map(scheduleItem).join('')||'<div class="empty">Nenhum serviço atrasado.</div>';renderDayDetails()}
function selectDay(ds){selectedDay=ds;renderAgenda()}
function renderDayDetails(){if(!selectedDay){$('#dayDetails').innerHTML='<p class="minor">Toque em um dia para ver os serviços previstos e as visitas realizadas.</p>';return}const planned=DB.offerings.filter(o=>o.nextDue===selectedDay),done=DB.services.filter(s=>s.date===selectedDay);$('#dayDetails').innerHTML=`<div class="sectionTitle">${fmt(selectedDay)}</div><div class="list">`+planned.map(scheduleItem).join('')+done.map(s=>`<div class="item"><div class="left"><div class="title">${esc(client(s.clientId)?.name)}</div><div class="serviceName">${esc(visitName(s))}</div><div class="meta">Realizado • ${money(s.amount)}</div></div></div>`).join('')+(!planned.length&&!done.length?'<div class="empty">Nenhuma visita neste dia.</div>':'')+'</div>'}
function changeMonth(n){calCursor.setMonth(calCursor.getMonth()+n);renderAgenda()}
function exportData(){const blob=new Blob([JSON.stringify(DB,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='JK_Gestao_Backup_'+M.today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const next=M.migrate(JSON.parse(await f.text()));if(confirm('Restaurar este backup e substituir os dados atuais? Salve um backup atual antes de continuar.'))await commit(db=>{for(const k of Object.keys(db))delete db[k];Object.assign(db,next)})}catch(e){alert(e.message)}e.target.value=''};
$('#clientSearch').oninput=renderClients;$('#offeringSearch').oninput=renderOfferings;$('#offeringFilter').onchange=renderOfferings;$('#historySearch').oninput=renderHistory;
bootShared();window.addEventListener('focus',refreshCloud);setInterval(refreshCloud,15000);
