const {readFileSync}=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm'),{randomUUID}=require('node:crypto');
const M=require('../data-model');let passed=0;function test(name,fn){fn();passed++;console.log('PASS '+name)}
function fixture(){return {clients:[{id:'c',name:'Cliente',address:'Rua 1'}],offerings:[{id:'o1',clientId:'c',name:'Corte',freq:'Quinzenal',value:180,nextDue:'2026-09-08'},{id:'o2',clientId:'c',name:'Brita',freq:'Avulso',value:900,nextDue:'2026-09-08'}],services:[],payments:[],meta:{schemaVersion:3}}}
function complete(d,o,id,date='2026-09-07',amount=180){return M.complete(d,o,{id,date,amount},'2026-10-01')}
test('frequências e fins de semana mantidos',()=>{for(const [date,freq,next] of [['2026-09-02','A cada 10 dias','2026-09-14'],['2026-08-07','Quinzenal','2026-08-24'],['2026-08-07','Mensal','2026-09-07'],['2026-08-07','Avulso','']])assert.equal(M.nextDate(date,freq),next)});
test('cadastro de cliente/serviço não inventa visitas e impede duplicação',()=>{const d=fixture();M.saveOffering(d,{id:'o3',clientId:'c',name:'Poda',freq:'Mensal',value:100,nextDue:''});assert.equal(d.clients.length,1);assert.equal(d.services.length,0);assert.throws(()=>M.saveClient(d,{id:'dup',name:' CLÍENTE ',address:'Outra'}),/já está/);assert.throws(()=>M.saveOffering(d,{id:'dup',clientId:'c',name:'córte',freq:'Mensal',value:250}),/já existe/)});
test('serviços do mesmo cliente têm agenda e cobrança independentes',()=>{const d=fixture();complete(d,'o1','v1');assert.equal(M.totalPending(d),0);assert.equal(d.offerings[0].nextDue,'2026-09-22');assert.equal(d.offerings[1].nextDue,'2026-09-08');complete(d,'o2','v2','2026-09-07',900);assert.equal(d.clients.length,1);assert.equal(d.services.length,2);assert.equal(M.totalPending(d),900);assert.equal(d.offerings[1].nextDue,'');assert.equal(d.services[0].cyclePosition,1)});
test('bloqueia mesmo atendimento duas vezes sem bloquear serviços distintos no dia',()=>{const d=fixture();complete(d,'o1','v1');assert.throws(()=>complete(d,'o1','vdup'),/já possui/);complete(d,'o2','v2');assert.equal(d.services.length,2)});
test('ciclo quinzenal pertence ao serviço, inclusive quando há outro quinzenal',()=>{const d=fixture();d.offerings[1].freq='Quinzenal';complete(d,'o1','v1');complete(d,'o2','v2');assert.equal(M.totalPending(d),0);complete(d,'o1','v3','2026-09-22');assert.equal(d.services[2].cycleFirstId,'v1');assert.equal(d.services[1].cycleClosed,false);assert.equal(M.totalPending(d,'2026-10-01'),180)});
test('pagar e desfazer mantêm visita, valor, serviço e ciclo corretos',()=>{const d=fixture();complete(d,'o1','v1');complete(d,'o1','v2','2026-09-22');complete(d,'o2','v3','2026-09-23',900);M.pay(d,'v2',{paymentId:'p',date:'2026-09-23'},'2026-10-01');assert.equal(M.paidMonth(d,'2026-09-30'),180);assert.equal(M.totalPending(d,'2026-10-01'),900);assert.equal(d.payments[0].offeringId,'o1');assert.throws(()=>M.pay(d,'v2',{paymentId:'p2',date:'2026-09-23'},'2026-10-01'));M.undo(d,'p');assert.equal(M.paidMonth(d,'2026-09-30'),0);assert.equal(M.totalPending(d,'2026-10-01'),1080);assert.equal(d.services.length,3);assert.equal(d.services[0].cycleClosed,true)});
test('valor zero e pagamentos históricos sem data não são inventados',()=>{const d=fixture();complete(d,'o2','v1','2026-09-07',0);M.pay(d,'v1',{paymentId:'p1',date:'2026-09-07'},'2026-10-01');assert.equal(d.payments[0].amount,0);M.undo(d,'p1');d.services[0].paid=true;M.undoLegacy(d,'v1','legacy');assert.equal(d.payments[1].date,null);assert.ok(d.payments[1].reversedAt)});
test('editar serviço/cliente não altera visitas ou pagamentos antigos',()=>{const d=fixture();complete(d,'o2','v1','2026-09-07',900);M.pay(d,'v1',{paymentId:'p',date:'2026-09-07'},'2026-10-01');const visits=JSON.stringify(d.services),payments=JSON.stringify(d.payments);M.saveOffering(d,{clientId:'c',name:'Brita nova',value:1000,freq:'Mensal',nextDue:'2026-10-07'},'o2');M.saveClient(d,{name:'Cliente editado',address:'Rua 2'},'c');assert.equal(JSON.stringify(d.services),visits);assert.equal(JSON.stringify(d.payments),payments)});
test('datas inválidas/futuras, pagamento anterior e vínculo quebrado são rejeitados',()=>{const d=fixture();assert.throws(()=>complete(d,'o1','v1','2026-02-31'));assert.throws(()=>complete(d,'o1','v1','2027-01-01'));complete(d,'o2','v1');assert.throws(()=>M.pay(d,'v1',{paymentId:'p',date:'2026-09-06'}));d.services[0].offeringId='missing';assert.throws(()=>M.validate(d))});
test('migração não cria visita a partir de data no cadastro',()=>{const d=M.migrate({clients:[{id:'x',name:'X',lastDone:'2026-01-01',freq:'Mensal',value:50}],services:[],payments:[]});assert.equal(d.services.length,0);assert.equal(d.offerings.length,1);assert.equal(d.migrationArchive.structureV3.source.clients[0].lastDone,'2026-01-01')});
if(process.argv[2])test('dados reais: união revisada, nenhum pagamento perdido, totais invariantes e migração idempotente',()=>{
 const old=JSON.parse(readFileSync(process.argv[2])),d=M.migrate(old),archive=d.migrationArchive.structureV3;
 assert.equal(d.clients.length,22);assert.equal(d.offerings.length,23);assert.equal(d.services.length,13);assert.equal(d.payments.length,4);assert.deepEqual(archive.source,old);assert.deepEqual(M.migrate(d),d);
 assert.equal(M.totalPending(old,'2026-09-07'),M.totalPending(d,'2026-09-07'));assert.equal(M.paidMonth(old,'2026-09-07'),M.paidMonth(d,'2026-09-07'));
 for(const p of old.payments){const n=d.payments.find(x=>x.id===p.id);for(const k of ['date','amount','reversedAt'])assert.equal(n[k],p[k]);assert.ok(d.services.find(s=>s.id===n.serviceId&&s.offeringId===n.offeringId&&s.clientId===n.clientId))}
 for(const s of d.services){const prev=old.services.find(x=>x.id===s.id);assert.ok(prev);for(const k of ['date','amount','paid','chargeDue','cyclePosition','cycleClosed'])assert.equal(s[k],prev[k])}
 for(const name of ['Rede feminina','Alexandre']){const c=d.clients.find(c=>c.name===name),visits=d.services.filter(s=>s.clientId===c.id);assert.equal(new Set(visits.map(s=>s.date)).size,visits.length)}
 const sesc=d.clients.find(c=>c.name==='Sesc Forquilhinha'),offs=d.offerings.filter(o=>o.clientId===sesc.id);assert.deepEqual(offs.map(o=>o.value),[900,1591]);assert.equal(offs.filter(o=>o.nextDue==='2026-09-10').length,2);
 const protectedInput=JSON.parse(JSON.stringify(old));protectedInput.payments.find(p=>p.id==='7d96a84c-73f8-4c29-bb52-c6ff43bc10d5').amount=250;assert.equal(M.migrate(protectedInput).services.length,14);
});
async function testUI(){
 const html=readFileSync(require('path').join(__dirname,'../index.html'),'utf8'),ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1])),elements=new Map();
 function el(s){if(s==='dialog[open]')return null;assert.ok(ids.has(s.slice(1)),'DOM selector exists: '+s);if(!elements.has(s))elements.set(s,{value:'',textContent:'',innerHTML:'',disabled:false,showModal(){this.open=true},close(){this.open=false}});return elements.get(s)}
 let server=fixture(),rev='2026-09-07T10:00:00Z',conflict=false,failure=false,patches=0;const alerts=[];
 const ctx=vm.createContext({JKModel:M,document:{querySelector:el,querySelectorAll:()=>[]},localStorage:{getItem:()=>null,setItem(){}},window:{addEventListener(){}},setInterval(){},crypto:{randomUUID},console,alert:s=>alerts.push(s),confirm:()=>true,fetch:async(url,opt={})=>{
 if(opt.method==='PATCH'){patches++;assert.ok(url.includes('updated_at=eq.'+encodeURIComponent(rev)));if(failure)return {ok:false};if(conflict)return {ok:true,json:async()=>[]};server=JSON.parse(opt.body).data;rev=JSON.parse(opt.body).updated_at;}return {ok:true,json:async()=>[{data:server,updated_at:rev}]};
 }});for(const id of ['clientDialog','offeringDialog','doneDialog','paymentDialog'])ctx[id]=el('#'+id);
 const run=s=>vm.runInContext(s,ctx);run(readFileSync(require('path').join(__dirname,'../app.js'),'utf8').replace('bootShared();window','window'));
 await run('bootShared()');run("showOfferings('c');openDone('o1')");assert.ok(el('#doneOfferingSelect').innerHTML.includes('Brita'));assert.equal(el('#doneOfferingSelect').value,'o1');run("selectDay('2026-09-08')");assert.equal((el('#dayDetails').innerHTML.match(/Registrar realizado/g)||[]).length,2);
 el('#doneDate').value='2026-09-07';await run('confirmDone()');assert.equal(server.services.length,1);assert.equal(server.services[0].offeringId,'o1');assert.ok(patches);const before=JSON.stringify(server);failure=true;assert.equal(await run("commit(db=>{db.clients[0].name='Lost'})"),false);assert.equal(JSON.stringify(server),before);assert.equal(run('DB.clients[0].name'),'Cliente');failure=false;conflict=true;assert.equal(await run("commit(db=>{db.clients[0].name='Stale'})"),false);assert.equal(run('DB.clients[0].name'),'Cliente');assert.ok(alerts.length===2);
 console.log('PASS UI selects existing client/service, day details, atomic save and stale/failure protection');passed++;
}
testUI().then(()=>console.log(`${passed} testes passaram`)).catch(e=>{console.error(e);process.exitCode=1});
