const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const source=readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1].replace('bootShared();','');
function harness(data={clients:[],services:[],payments:[],meta:{version:1}}){
 const elements=new Map();const el=s=>{if(!elements.has(s))elements.set(s,{value:'',style:{},classList:{toggle(){}},showModal(){},close(){}});return elements.get(s)};
 const storage=new Map([['JK_GESTAO_MASTER',JSON.stringify(data)]]);
 const ctx=vm.createContext({document:{querySelector:el,querySelectorAll:()=>[]},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},window:{addEventListener(){}},setInterval(){},crypto:{randomUUID},console,confirm:()=>true,alert(){},clientDialog:el('#clientDialog'),doneDialog:el('#doneDialog')});
 vm.runInContext(source,ctx);const run=s=>vm.runInContext(s,ctx);run("today=()=> '2026-09-07'");
 return {run,ctx,el,snapshot:()=>JSON.parse(run('JSON.stringify(DB)'))};
}
let passed=0;
function test(name,fn){fn();console.log('PASS '+name);passed++}
const c={id:'rosi',name:'Rosi',freq:'Quinzenal',value:180,lastDone:'2026-08-24',nextDue:'2026-09-08',seedStage:'2',seedPayment:'pending',customField:'preserved'};
const service={id:'second',clientId:'rosi',date:'2026-08-24',amount:180,chargeDue:true,paid:false,cycleClosed:true,cyclePosition:2,note:'Histórico inicial • 2ª visita'};
const fixture=()=>({clients:[{...c}],services:[{...service}],payments:[],meta:{version:1,visitsOrganization:2}});
test('10 dias, sábados, domingos, quinzenal, mensal e avulso',()=>{const h=harness();for(const [date,freq,want] of [['2026-09-01','A cada 10 dias','2026-09-11'],['2026-09-02','A cada 10 dias','2026-09-14'],['2026-09-03','A cada 10 dias','2026-09-14'],['2026-08-07','Quinzenal','2026-08-24'],['2026-08-07','Mensal','2026-09-07'],['2026-08-07','Avulso','']])assert.equal(h.run(`nextDate('${date}','${freq}')`),want)});
test('cancelar, pagar, impedir duplicação, desfazer e receber novamente',()=>{const h=harness(fixture());h.ctx.confirm=()=>false;h.run("markPaid('rosi','second')");assert.deepEqual(h.snapshot(),fixture());h.ctx.confirm=()=>true;h.run("markPaid('rosi','second')");assert.equal(h.run('paidThisMonth()'),180);assert.equal(h.run('totalPending()'),0);assert.equal(h.snapshot().payments[0].clientName,'Rosi');h.run("markPaid('rosi','second')");assert.equal(h.snapshot().payments.length,1);h.ctx.confirm=()=>false;h.run('undoPayment(DB.payments[0].id)');assert.equal(h.run('paidThisMonth()'),180);h.ctx.confirm=()=>true;h.run('undoPayment(DB.payments[0].id)');assert.equal(h.run('paidThisMonth()'),0);assert.equal(h.run('totalPending()'),180);assert.deepEqual(h.snapshot().services,fixture().services);h.run('undoPayment(DB.payments[0].id)');assert.equal(h.run('totalPending()'),180);h.run("markPaid('rosi','second')");assert.equal(h.run('paidThisMonth()'),180)});
test('pagamento não fecha a primeira visita de um novo ciclo',()=>{const data=fixture();data.services.push({id:'first',clientId:'rosi',date:'2026-09-01',chargeDue:false,paid:true,cycleClosed:false,cyclePosition:1});const h=harness(data);h.run("markPaid('rosi','second');undoPayment(DB.payments[0].id)");assert.equal(h.snapshot().services[1].cycleClosed,false)});
test('edição de frequência preserva serviços, pagamentos e campos adicionais',()=>{const h=harness(fixture());h.run("openClient('rosi')");h.el('#cFreq').value='A cada 10 dias';h.run("$('#cFreq').onchange();saveClient()");assert.deepEqual(h.snapshot().services,fixture().services);assert.deepEqual(h.snapshot().payments,[]);assert.equal(h.snapshot().clients[0].customField,'preserved');assert.equal(h.snapshot().clients[0].nextDue,'2026-09-03')});
test('agendamento vencido não cobra; realização usa data real +10 dias',()=>{const h=harness({clients:[{...c,freq:'A cada 10 dias',lastDone:'',nextDue:'2026-08-01'}],services:[],payments:[]});assert.equal(h.run('totalPending()'),0);assert.equal(h.run('agendaState(DB.clients[0]).text'),'Atrasado • não realizado');h.run("openDone('rosi')");h.el('#doneDate').value='2026-09-03';h.run('confirmDone()');assert.equal(h.run('totalPending()'),180);assert.equal(h.snapshot().clients[0].nextDue,'2026-09-14')});
test('serviço futuro não pode ser registrado nem cobrado',()=>{const h=harness(fixture());const before=h.snapshot();h.run("openDone('rosi')");h.el('#doneDate').value='2026-10-01';h.run('confirmDone()');assert.deepEqual(h.snapshot(),before);h.run("DB.services[0].date='2026-10-01'");assert.equal(h.run('totalPending()'),0)});
test('quinzenal só cobra segunda visita, mesmo depois de desfazer pagamento anterior',()=>{const h=harness(fixture());h.run("markPaid('rosi','second');undoPayment(DB.payments[0].id);openDone('rosi');confirmDone()");assert.equal(h.snapshot().services[1].chargeDue,false);h.run("openDone('rosi');confirmDone()");assert.equal(h.snapshot().services[2].chargeDue,true);assert.equal(h.run('totalPending()'),360)});
test('valor zero permanece zero ao receber',()=>{const d=fixture();d.services[0].amount=0;const h=harness(d);h.run("markPaid('rosi','second')");assert.equal(h.snapshot().payments[0].amount,0)});
test('migração adiciona só visita ausente, mantém pagamentos e é idempotente',()=>{
 const d={clients:[{...c,id:'old',freq:'Mensal',lastDone:'2026-08-01',seedPayment:'paid'}],services:[],payments:[],extra:{keep:true}};
 const h=harness(d),first=h.snapshot();assert.equal(first.services.length,1);assert.equal(first.services[0].paid,true);assert.deepEqual(first.payments,[]);assert.deepEqual(first.extra,d.extra);h.run('DB=normalizeDB(DB)');assert.deepEqual(h.snapshot(),first);h.run('renderHistory()');assert.ok(h.el('#historyList').innerHTML.includes('não informada no histórico'));h.run('undoLegacyPayment(DB.services[0].id)');assert.equal(h.run('totalPending()'),180);assert.equal(h.run('paidThisMonth()'),0);assert.equal(h.snapshot().services.length,1);assert.ok(h.snapshot().payments[0].reversedAt);
});
test('Clientes só edita dados fixos e novo cadastro não cria visita',()=>{
 const h=harness();h.run('openClient()');h.el('#cName').value='Novo';h.el('#cCity').value='Rua 1';h.el('#cFreq').value='Mensal';h.el('#cValue').value='100';h.run('saveClient()');assert.equal(h.snapshot().clients[0].address,'Rua 1');assert.equal(h.snapshot().services.length,0);assert.equal(h.snapshot().clients[0].nextDue,'');
});
test('visita mensal antiga não recua a próxima data; valor zero é preservado',()=>{
 const d=fixture();d.clients[0].freq='Mensal';const h=harness(d);h.run("openDone('rosi')");h.el('#doneDate').value='2026-08-01';h.el('#doneValue').value='0';h.run('confirmDone()');assert.equal(h.snapshot().services[1].amount,0);assert.equal(h.snapshot().clients[0].lastDone,'2026-08-24');assert.equal(h.snapshot().clients[0].nextDue,'2026-09-24');
});
test('primeira visita acompanha pagamento e estorno do ciclo vinculado',()=>{
 const h=harness(fixture());h.run("openDone('rosi');confirmDone();openDone('rosi');confirmDone()");const d=h.snapshot();assert.equal(d.services[2].cycleFirstId,d.services[1].id);h.run('markPaid(DB.clients[0].id,DB.services[2].id);renderHistory()');assert.equal(h.run('cycleCharge(DB.services[1]).paid'),true);h.run('undoPayment(DB.payments[0].id)');assert.equal(h.run('cycleCharge(DB.services[1]).paid'),false);assert.equal(h.snapshot().services.length,3);
});
test('dia selecionado lista serviços realizados e previstos',()=>{
 const h=harness(fixture());h.run("selectDay('2026-08-24')");assert.ok(h.el('#dayDetails').innerHTML.includes('Realizado'));h.run("selectDay('2026-09-08')");assert.ok(h.el('#dayDetails').innerHTML.includes('Registrar realizado'));assert.ok(h.el('#calendar').innerHTML.includes('aria-label='));
});
if(process.argv[2])test('dados existentes preservados e migração repetível',()=>{const d=JSON.parse(readFileSync(process.argv[2]));const h=harness(d);h.run('renderAll()');assert.deepEqual(h.snapshot().clients,d.clients);assert.deepEqual(h.snapshot().services.slice(0,d.services.length),d.services);assert.deepEqual(h.snapshot().payments,d.payments);assert.deepEqual(h.snapshot(),JSON.parse(h.run('JSON.stringify(normalizeDB(DB))')));const expected=d.payments.filter(p=>!p.reversedAt&&(p.date||'').startsWith('2026-09')).reduce((n,p)=>n+p.amount,0);assert.equal(h.run('paidThisMonth()'),expected);for(const p of d.payments.filter(p=>!p.reversedAt)){assert.ok(h.el('#receivedList').innerHTML.includes(d.clients.find(c=>c.id===p.clientId).name));const t=harness(d);t.run(`undoPayment('${p.id}')`);assert.equal(t.snapshot().services.length,h.snapshot().services.length);assert.equal(t.snapshot().clients.length,d.clients.length)}});
console.log(`${passed} testes passaram`);
