const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const {randomUUID}=require('node:crypto');
const source=readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1].replace('bootShared();','');
function harness(data={clients:[],services:[],payments:[],meta:{version:1}}){
 const elements=new Map();const el=s=>{if(!elements.has(s))elements.set(s,{value:'',style:{},classList:{toggle(){}},showModal(){},close(){}});return elements.get(s)};
 const storage=new Map([['JK_GESTAO_MASTER',JSON.stringify(data)]]);
 const ctx=vm.createContext({document:{querySelector:el,querySelectorAll:()=>[]},localStorage:{getItem:k=>storage.get(k),setItem:(k,v)=>storage.set(k,v)},window:{addEventListener(){}},setInterval(){},crypto:{randomUUID},console,confirm:()=>true,alert(){},clientDialog:el('#clientDialog'),doneDialog:el('#doneDialog')});
 vm.runInContext(source,ctx);const run=s=>vm.runInContext(s,ctx);run("today=()=> '2026-09-07'");
 return {run,ctx,el,snapshot:()=>JSON.parse(run('JSON.stringify(DB)'))};
}
let passed=0;
function test(name,fn){fn();console.log('PASS '+name);passed++}
const c={id:'rosi',name:'Rosi',freq:'Quinzenal',value:180,lastDone:'2026-08-24',nextDue:'2026-09-08',seedStage:'2',seedPayment:'pending',customField:'preserved'};
const service={id:'second',clientId:'rosi',date:'2026-08-24',amount:180,chargeDue:true,paid:false,cycleClosed:true,cyclePosition:2,note:'Histórico inicial • 2ª visita'};
const fixture=()=>({clients:[{...c}],services:[{...service}],payments:[],meta:{version:1}});
test('10 dias, sábados, domingos, quinzenal, mensal e avulso',()=>{const h=harness();for(const [date,freq,want] of [['2026-09-01','A cada 10 dias','2026-09-11'],['2026-09-02','A cada 10 dias','2026-09-14'],['2026-09-03','A cada 10 dias','2026-09-14'],['2026-08-07','Quinzenal','2026-08-24'],['2026-08-07','Mensal','2026-09-07'],['2026-08-07','Avulso','']])assert.equal(h.run(`nextDate('${date}','${freq}')`),want)});
test('cancelar, pagar, impedir duplicação, desfazer e receber novamente',()=>{const h=harness(fixture());h.ctx.confirm=()=>false;h.run("markPaid('rosi','second')");assert.deepEqual(h.snapshot(),fixture());h.ctx.confirm=()=>true;h.run("markPaid('rosi','second')");assert.equal(h.run('paidThisMonth()'),180);assert.equal(h.run('totalPending()'),0);assert.equal(h.snapshot().payments[0].clientName,'Rosi');h.run("markPaid('rosi','second')");assert.equal(h.snapshot().payments.length,1);h.ctx.confirm=()=>false;h.run('undoPayment(DB.payments[0].id)');assert.equal(h.run('paidThisMonth()'),180);h.ctx.confirm=()=>true;h.run('undoPayment(DB.payments[0].id)');assert.equal(h.run('paidThisMonth()'),0);assert.equal(h.run('totalPending()'),180);assert.deepEqual(h.snapshot().services,fixture().services);h.run('undoPayment(DB.payments[0].id)');assert.equal(h.run('totalPending()'),180);h.run("markPaid('rosi','second')");assert.equal(h.run('paidThisMonth()'),180)});
test('pagamento não fecha a primeira visita de um novo ciclo',()=>{const data=fixture();data.services.push({id:'first',clientId:'rosi',date:'2026-09-01',chargeDue:false,paid:true,cycleClosed:false,cyclePosition:1});const h=harness(data);h.run("markPaid('rosi','second');undoPayment(DB.payments[0].id)");assert.equal(h.snapshot().services[1].cycleClosed,false)});
test('edição de frequência preserva serviços, pagamentos e campos adicionais',()=>{const h=harness(fixture());h.run("openClient('rosi')");h.el('#cFreq').value='A cada 10 dias';h.run("$('#cFreq').onchange();saveClient()");assert.deepEqual(h.snapshot().services,fixture().services);assert.deepEqual(h.snapshot().payments,[]);assert.equal(h.snapshot().clients[0].customField,'preserved');assert.equal(h.snapshot().clients[0].nextDue,'2026-09-03')});
test('agendamento vencido não cobra; realização usa data real +10 dias',()=>{const h=harness({clients:[{...c,freq:'A cada 10 dias',nextDue:'2026-08-01'}],services:[],payments:[]});assert.equal(h.run('totalPending()'),0);assert.equal(h.run('agendaState(DB.clients[0]).text'),'Atrasado • não realizado');h.run("openDone('rosi')");h.el('#doneDate').value='2026-09-03';h.run('confirmDone()');assert.equal(h.run('totalPending()'),180);assert.equal(h.snapshot().clients[0].nextDue,'2026-09-14')});
test('serviço futuro não pode ser registrado nem cobrado',()=>{const h=harness(fixture());const before=h.snapshot();h.run("openDone('rosi')");h.el('#doneDate').value='2026-10-01';h.run('confirmDone()');assert.deepEqual(h.snapshot(),before);h.run("DB.services[0].date='2026-10-01'");assert.equal(h.run('totalPending()'),0)});
test('quinzenal só cobra segunda visita, mesmo depois de desfazer pagamento anterior',()=>{const h=harness(fixture());h.run("markPaid('rosi','second');undoPayment(DB.payments[0].id);openDone('rosi');confirmDone()");assert.equal(h.snapshot().services[1].chargeDue,false);h.run("openDone('rosi');confirmDone()");assert.equal(h.snapshot().services[2].chargeDue,true);assert.equal(h.run('totalPending()'),360)});
test('valor zero permanece zero ao receber',()=>{const d=fixture();d.services[0].amount=0;const h=harness(d);h.run("markPaid('rosi','second')");assert.equal(h.snapshot().payments[0].amount,0)});
if(process.argv[2])test('dados existentes carregam e renderizam sem nenhuma alteração',()=>{const d=JSON.parse(readFileSync(process.argv[2]));const h=harness(d);h.run('renderAll()');assert.deepEqual(h.snapshot(),d);const expected=d.payments.filter(p=>p.date.startsWith('2026-09')).reduce((n,p)=>n+p.amount,0);assert.equal(h.run('paidThisMonth()'),expected);for(const p of d.payments){assert.ok(h.el('#receivedList').innerHTML.includes(d.clients.find(c=>c.id===p.clientId).name));const t=harness(d);t.run(`undoPayment('${p.id}')`);assert.equal(t.snapshot().services.length,d.services.length);assert.equal(t.snapshot().clients.length,d.clients.length)}});
console.log(`${passed} testes passaram`);
